# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_expert.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11test_expert.proto\"\x15\n\x05Input\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x16\n\x06Output\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32&\n\x06\x45xpert\x12\x1c\n\x07\x45xecute\x12\x06.Input\x1a\x07.Output\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_expert_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUT']._serialized_start=21
  _globals['_INPUT']._serialized_end=42
  _globals['_OUTPUT']._serialized_start=44
  _globals['_OUTPUT']._serialized_end=66
  _globals['_EXPERT']._serialized_start=68
  _globals['_EXPERT']._serialized_end=106
# @@protoc_insertion_point(module_scope)
