# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shard_envoy.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11shard_envoy.proto\"\x1d\n\x07TestIns\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\"+\n\tShardOuts\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08metadata\x18\x02 \x01(\x0c\"\x07\n\x05\x45mpty2k\n\nShardEnvoy\x12\x1b\n\x05Start\x12\x08.TestIns\x1a\x06.Empty\"\x00\x12\x1f\n\x0bSignalReady\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x1f\n\x07Receive\x12\n.ShardOuts\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shard_envoy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TESTINS']._serialized_start=21
  _globals['_TESTINS']._serialized_end=50
  _globals['_SHARDOUTS']._serialized_start=52
  _globals['_SHARDOUTS']._serialized_end=95
  _globals['_EMPTY']._serialized_start=97
  _globals['_EMPTY']._serialized_end=104
  _globals['_SHARDENVOY']._serialized_start=106
  _globals['_SHARDENVOY']._serialized_end=213
# @@protoc_insertion_point(module_scope)
