# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moe_shard.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmoe_shard.proto\"$\n\x06Inputs\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04jobs\x18\x02 \x01(\x0c\"(\n\x07Outputs\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07\x61rr_map\x18\x02 \x01(\x0c\x32*\n\x08MoeShard\x12\x1e\n\x07\x45xecute\x12\x07.Inputs\x1a\x08.Outputs\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moe_shard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUTS']._serialized_start=19
  _globals['_INPUTS']._serialized_end=55
  _globals['_OUTPUTS']._serialized_start=57
  _globals['_OUTPUTS']._serialized_end=97
  _globals['_MOESHARD']._serialized_start=99
  _globals['_MOESHARD']._serialized_end=141
# @@protoc_insertion_point(module_scope)
