# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concurrent_shard.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63oncurrent_shard.proto\"\x17\n\x07TestIns\x12\x0c\n\x04secs\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2.\n\x0f\x43oncurrentShard\x12\x1b\n\x05Start\x12\x08.TestIns\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'concurrent_shard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TESTINS']._serialized_start=26
  _globals['_TESTINS']._serialized_end=49
  _globals['_EMPTY']._serialized_start=51
  _globals['_EMPTY']._serialized_end=58
  _globals['_CONCURRENTSHARD']._serialized_start=60
  _globals['_CONCURRENTSHARD']._serialized_end=106
# @@protoc_insertion_point(module_scope)
