# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shard.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bshard.proto\"J\n\tShardOuts\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x11\n\tblock_num\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0f\n\x07\x61rr_map\x18\x04 \x01(\x0c\"=\n\x06Inputs\x12\x10\n\x08n_layers\x18\x01 \x01(\x05\x12\r\n\x05\x64\x65lay\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2H\n\x05Shard\x12\x1f\n\x07Receive\x12\n.ShardOuts\x1a\x06.Empty\"\x00\x12\x1e\n\tStartTest\x12\x07.Inputs\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SHARDOUTS']._serialized_start=15
  _globals['_SHARDOUTS']._serialized_end=89
  _globals['_INPUTS']._serialized_start=91
  _globals['_INPUTS']._serialized_end=152
  _globals['_EMPTY']._serialized_start=154
  _globals['_EMPTY']._serialized_end=161
  _globals['_SHARD']._serialized_start=163
  _globals['_SHARD']._serialized_end=235
# @@protoc_insertion_point(module_scope)
